[package]
name = "viewp"
version = "0.1.1"
authors = ["SecretShangri-La <byobu@vivaldi.net>"]
edition = "2018"
license = "MIT"
description = "A program is get any argument, that generates prime. it argument be number. This Program is Test Stage."


[dependencies]
